### ISSUE TITLE
left side (streams or top player)

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/LuxSmash#14]

**Comment by Arnaud-Burn** [comment]
Possible both ?
If not, I'd rather say Stream

**Comment by Yoshi20** [comment]
The top player must be hard coded or added at a later time, when there are some data in the LuxSmash database.

As for the streams: The problem is that I can only get streams in a specific language.
I'm currently using 'lb' but it does not look like there are any streams using this language.

Any ideas? It can also be something different then streams or top players.

**Comment by Arnaud-Burn** [comment]
Another option would be to hardcode so the streams too...
Not that great but I don't think that Twitch will update a "Luxbembourgish" language and more; it's pretty much not used.
most often is French, English or German (but the results will be fakes for LUxembourg...)

**Comment by Arnaud-Burn** [comment]
Another option; could we re-use the players "Twitch" data to placed them in ?
If I'm a user or a Team with a Twitch account on my profile page, can this be placed in the Live stream instead of scanning for a language ?

**Comment by Yoshi20** [comment]
See: https://dev.twitch.tv/docs/api/reference#get-streams

Not tested yet but I think it's possible to get up to 100 specific users.
However there is no management for such specific streamer-users yet.
I may implement it in the future but depending on the work, interest and benefit it may cost the users a little (e.g 1-5 Euros / month or so)

**Comment by Arnaud-Burn** [comment]
Ok, so let's get that HC for now; I'll provide you a list of Lux streamers and orgas

**Comment by Arnaud-Burn** [comment]
SSB LUX STREAMERS LIST (UPDATE: 07/04)

- Letzsmash_SSB
- sweetspotasbl
- lestv_lu
