### ISSUE TITLE
Rankings

### ISSUE THREAD

**Issue by Yoshi20** [Yoshi20/LuxSmash#17]

**Comment by Arnaud-Burn** [comment]
at first, it will be an excell file under this link : pr.luxsmash.lu
That way, we can update it easily without changing the link

Would that works for you ?

**Comment by Yoshi20** [comment]
You do not have any PR like on: https://www.germanysmash.de/rankings 
or canton specific rankings?

I actually don't think an excel is a good way to go (does not match with the rest of the page) :D
I can request specific data or an other page and show it in an iframe (like on http://www.smashultimate.fr/rankings) or I can hard code it and easily update it. Since normally the ranking do not change that often, or do they?

**Comment by Arnaud-Burn** [comment]
Badfully, not at the moment.
I've talked yesterday with the organization that used to make the PR for Luxembourg (I'm part of it too)
We will try to update it asap and find a new way (I've made my point with them for a graphical one; easier and nicer)
The other option would be the braacket website.

So still in discussion

We just place a "Comming Soon" text I'd rather say for now

**Comment by Arnaud-Burn** [comment]
Here are the link to the PR

https://www.letz-smash.lu/wp-content/uploads/2022/05/LUX-PR-2022-WinterSpring.jpg
