### ISSUE TITLE
Social links in the footer

### ISSUE THREAD

**Issue by Arnaud-Burn** [Yoshi20/LuxSmash#7]
Could you place the Social Icon links nearby the LetzSmash logo to narrow the Footer ?

![image](https://user-images.githubusercontent.com/7067777/161496956-5a2ee66a-6432-40d5-acef-12e735c94c5e.png)

**Comment by Yoshi20** [comment]
Not in the mobile view :X
And there's also not much space left with "Feedback & Questions".

**Comment by Yoshi20** [comment]
<img width="962" alt="Bildschirmfoto 2022-04-04 um 14 44 15" src="https://user-images.githubusercontent.com/1472752/161546240-e878eb9d-d466-4577-8fae-71e2e6adf1db.png">
I moved them 20px up.

<br>
<br>
Here's the mobile view:
<img width="327" alt="Bildschirmfoto 2022-04-04 um 14 45 03" src="https://user-images.githubusercontent.com/1472752/161546423-ccb96c93-69fc-4167-9182-7a44a377f577.png">

**Comment by Arnaud-Burn** [comment]
ok, perfect for me
